export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_STUDENT_REQUEST = "REGISTER_STUDENT_REQUEST";
export const REGISTER_STUDENT_SUCCESS = "REGISTER_STUDENT_SUCCESS";
export const REGISTER_STUDENT_FAIL = "REGISTER_STUDENT_FAIL";

export const LOAD_STUDENT_REQUEST = "LOAD_STUDENT_REQUEST";
export const LOAD_STUDENT_SUCCESS = "LOAD_STUDENT_SUCCESS";
export const LOAD_STUDENT_FAIL = "LOAD_STUDENT_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const ALL_STUDENTS_REQUEST = "ALL_STUDENTS_REQUEST";
export const ALL_STUDENTS_SUCCESS = "ALL_STUDENTS_SUCCESS";
export const ALL_STUDENTS_FAIL = "ALL_STUDENTS_FAIL";

export const ALL_OWNERS_REQUEST = "ALL_OWNERS_REQUEST";
export const ALL_OWNERS_SUCCESS = "ALL_OWNERS_SUCCESS";
export const ALL_OWNERS_FAIL = "ALL_OWNERS_FAIL";

export const STUDENT_DETAILS_REQUEST = "STUDENT_DETAILS_REQUEST";
export const STUDENT_DETAILS_SUCCESS = "STUDENT_DETAILS_SUCCESS";
export const STUDENT_DETAILS_FAIL = "STUDENT_DETAILS_FAIL";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET";
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL";
export const DELETE_STUDENT_RESET = "DELETE_STUDENT_RESET";

export const DELETE_OWNER_REQUEST = "DELETE_OWNER_REQUEST";
export const DELETE_OWNER_SUCCESS = "DELETE_OWNER_SUCCESS";
export const DELETE_OWNER_FAIL = "DELETE_OWNER_FAIL";
export const DELETE_OWNER_RESET = "DELETE_OWNER_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";